### ISSUE TITLE
Improve html email to change password

### ISSUE THREAD

**Issue by alexrobaina** [alexrobaina/api-pets-love#23]
**The goal of this task** it is mejorar el html y css del email para resetear el password.

You can work on the forgotPassword.templates.ts and use the urlResetPassword variable to redirect to the reset password

This is the design:
![Screen Shot 2020-10-08 at 02 39 47](https://user-images.githubusercontent.com/30770802/95419248-a27a1000-090f-11eb-84a3-60be1882e410.png)

This is the image:
![page not found](https://user-images.githubusercontent.com/30770802/95419372-e3722480-090f-11eb-9c4a-e43e2b30747e.jpg)

This is font import url for title and text: 
@import 'https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;700&display=swap';

**Comment by hvsio** [comment]
Can you make the goal of the task more precise aka more English? :D is it mplementation of the design above + redirection?

**Comment by alexrobaina** [comment]
Hi @hvsio yes, of course, I am happy to add more information. Thank you very much for you interest. 
In this file forgotPassword.templates.ts you will see an html between ``

You only have to touch this file because the logic to send emails is done. 
😀

**Comment by hvsio** [comment]
you can assign it to me then

**Comment by hvsio** [comment]
could you add a label "hactoberfest" to your repo? They have changed the rules and otherwise it does not count...
