### ISSUE TITLE
Create docker file

### ISSUE THREAD

**Issue by alexrobaina** [alexrobaina/api-pets-love#80]
The gold of this issue is to dockerize the API

We need that developer to run Docker, automatically create DB, and make migrations.

**Comment by Adidem23** [comment]
Can You Explain More What features You Specifically want with Docker . I am ready to wrok with this issue

**Comment by Adidem23** [comment]
please Assign this issue to me @alexrobaina

**Comment by alexrobaina** [comment]
I @Adidem23 The idea is that API works with docker to help the developers build faster and easier, and it needs to work with .env and create the DB. 

This project uses node v16. 

Do you have more questions?
